services:
  - type: web
    name: marketing-markazi-hr-bot
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push && npx ts-node prisma/seed.ts && node dist/index.js
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        value: 8702937610:AAHXv9LjrDZTKsnpQq9nYQBBIRP_iaH-Sog
      - key: BOT_USERNAME
        value: marketingmarkazi_hr_bot
      - key: SUPPORT_USERNAME
        value: HR_MarketingMarkazi
      - key: HR_TELEGRAM_GROUP_ID
        value: "-1002923694952"
      - key: DATABASE_URL
        value: "file:./dev.db"
      - key: AMOCRM_SUBDOMAIN
        value: "31535142.amocrm.ru"
      - key: AMOCRM_CLIENT_ID
        value: "5e9a084b-da5b-4827-8720-65fcf3800721"
      - key: AMOCRM_CLIENT_SECRET
        value: "QUpOY8QE6cVZ3qEb6RkJMwD5b01zdKaVl0FktEr3ctZHdastml9M0oTcGJrUP1lq"
      - key: AMOCRM_ACCESS_TOKEN
        value: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjVhMjgxZjEzYmNkZTMzZWJhNDA0Y2ZlZjQwNDNjMzA2NDAyN2Y2ZWJkZjdkOWU3ZDViYTIwZTRhYzY0ODM4NjIwZjRkZmU1MDUzZTcwYTJiIn0.eyJhdWQiOiI1ZTlhMDg0Yi1kYTViLTQ4MjctODcyMC02NWZjZjM4MDA3MjEiLCJqdGkiOiI1YTI4MWYxM2JjZGUzM2ViYTQwNGNmZWY0MDQzYzMwNjQwMjdmNmViZGY3ZDllN2Q1YmEyMGU0YWM2NDgzODYyMGY0ZGZlNTA1M2U3MGEyYiIsImlhdCI6MTc4NTUwMzc0NCwibmJmIjoxNzg1NTAzNzQ0LCJleHAiOjE4ODQ2NDMyMDAsInN1YiI6IjEwNjA3NTE0IiwiZ3JhbnRfdHlwZSI6IiIsImFjY291bnRfaWQiOjMxNTM1MTQyLCJiYXNlX2RvbWFpbiI6ImFtb2NybS5ydSIsInZlcnNpb24iOjIsInNjb3BlcyI6WyJwdXNoX25vdGlmaWNhdGlvbnMiLCJmaWxlcyIsImNybSIsIm5vdGlmaWNhdGlvbnMiXSwiaGFzaF91dWlkIjoiMWIzNmNjZjQtNmFkYi00YjdjLWJkMTAtZjJjNzBiNGJlMzU5IiwiYXBpX2RvbWFpbiI6ImFwaS1iLmFtb2NybS5ydSJ9.TYk-uww1xgCgo24QSgETRW73mlGLPGF0MfHbLucB3iUlpQKg69sV0C5BtO3HemlPaQQ8EuvCNgbMj7r_S9U2pr_EIp_rmKwyr082XFbQEfUtx485T-WrDSXCe2E1i71YOX7IJl4nTD22rKqFSkYg8oV6LzxjasIM7YX6qricm3EQ-Ycuo1GmjlX7G8jnmViJHImzFbRayvacWTciIatfH8KpoxO1wjy1sOS0Y3ykg4GIvxhOIxCnks1zIYU3GmLq17ytoXN2Ldxh256AtuzeQoA06SthTud0yrCApG4yXD85G05-6MYwAeIRdzbhgvJY7V3OGNzdrwfKx_GFhHaaRw"
      - key: AMOCRM_PIPELINE_ID
        value: "10505546"
